
version: '3.10'

services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        ARCH: ${ARCH}
    volumes:
      - ./backend/:/backend/
    command: uvicorn shared.core.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - local-app-network

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    networks:
      - local-app-network

networks:
  local-app-network:

volumes:
  postgres_data:
